version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    depends_on:
        - db
    networks:
      - gateway

  db:
    environment:
      - MSSQL_SA_PASSWORD=vV5r9tn0M4@
      - ACCEPT_EULA=Y
    restart: always
    ports:
        - "1433:1433"
    networks:
      - gateway

networks:
  gateway: {}
