version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Desk.API/docker/Dockerfile
    ports:
     - "8000:80"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=vV5r9tn0M4@
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"
