version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}deskapi
    build:
      context: .
      dockerfile: Desk.API/docker/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest