version: '3.4'

services:
  dotnet:
    container_name: dotnet
    build:
      context: .
      dockerfile: Desk.API/docker/Dockerfile

  db:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest

  vue:
    container_name: vue
    build:
        context: ./desk.vue
        dockerfile: docker/Dockerfile
    